var mrk = [
    {
        name: 'ACTIVIDADES',
        folder: 'actividades',
        items: [
            {name:'UNIDAD 1',items:[{name:'El género dramático',link:'1',page:'10'},{name:'Escribir un pequeño texto dramático',link:'2',page:'19'},{name:'Lectura expresiva',link:'3',page:'20'},{name:'Honestidad intelectual, plagio y paráfrasis',link:'4',page:'22'},{name:'Honestidad intelectual, plagio y paráfrasis',link:'5',page:'23'},{name:'Honestidad intelectual, plagio y paráfrasis',link:'6',page:'27'},{name:'Formas de citación',link:'7',page:'28'},{name:'Formas de citación',link:'8',page:'31'},{name:'Oración compuesta por yuxtaposición',link:'9',page:'33'},{name:'Pronombres átonos y complementos directo e indirecto',link:'10',page:'34'},{name:'Pronombres átonos y complementos directo e indirecto',link:'11',page:'34'},{name:'Pronombres átonos y complementos directo e indirecto',link:'12',page:'35'},{name:'Evaluación sumativa',link:'13',page:'46'},]},
            {name:'UNIDAD 2',items:[{name:'Estructura interna de una obra del género dramático',link:'14',page:'52'},{name:'Estructura interna de una obra del género dramático',link:'15',page:'52'},{name:'Estructura interna de una obra del género dramático',link:'16',page:'55'},{name:'Estructura interna de una obra del género dramático',link:'17',page:'57'},{name:'Estructura externa de una obra del género dramático. Roles del montaje escénico',link:'18',page:'58'},{name:'Estructura externa de una obra del género dramático. Roles del montaje escénico',link:'19',page:'58'},{name:'Estructura externa de una obra del género dramático. Roles del montaje escénico',link:'20',page:'59'},{name:'Estructura externa de una obra del género dramático. Roles del montaje escénico',link:'21',page:'59'},{name:'Importancia de la oralidad en la comunicación',link:'22',page:'62'},{name:'Importancia de la oralidad en la comunicación',link:'23',page:'63'},{name:'Importancia de la oralidad en la comunicación',link:'24',page:'63'},{name:'Texto expositivo',link:'25',page:'64'},{name:'Texto expositivo',link:'26',page:'64'},{name:'Texto expositivo',link:'27',page:'64'},{name:'Texto expositivo',link:'28',page:'66'},{name:'Idea principal e ideas secundarias',link:'29',page:'68'},{name:'Idea principal e ideas secundarias',link:'30',page:'68'},{name:'Idea principal e ideas secundarias',link:'31',page:'69'},{name:'Cita textual larga',link:'32',page:'70'},{name:'Cita textual larga',link:'33',page:'70'},{name:'Cita textual larga',link:'34',page:'71'},{name:'Escritura de un texto expositivo',link:'35',page:'72'},{name:'Escritura de un texto expositivo',link:'36',page:'72'},{name:'Escritura de un texto expositivo',link:'37',page:'73'},{name:'Locuciones conjuntivas',link:'38',page:'74'},{name:'Locuciones conjuntivas',link:'39',page:'74'},{name:'Locuciones conjuntivas',link:'40',page:'75'},{name:'Diálogos directos e indirectos',link:'41',page:'76'},{name:'Diálogos directos e indirectos',link:'42',page:'76'},{name:'Diálogos directos e indirectos',link:'43',page:'77'},{name:'Registros de la lengua y estereotipos',link:'44',page:'80'},{name:'Registros de la lengua y estereotipos',link:'45',page:'80'},{name:'Registros de la lengua y estereotipos',link:'46',page:'83'},{name:'Evaluación sumativa',link:'47',page:'88'},]},
            {name:'UNIDAD 3',items:[{name:'Los subgéneros dramáticos menores',link:'48',page:'94'},{name:'Los subgéneros dramáticos menores',link:'49',page:'94'},{name:'Los subgéneros dramáticos menores',link:'50',page:'100'},{name:'La oratoria: declamación y discurso',link:'51',page:'104'},{name:'La oratoria: declamación y discurso',link:'52',page:'104'},{name:'La oratoria: declamación y discurso',link:'53',page:'105'},{name:'El informe de laboratorio o de experimento',link:'54',page:'106'},{name:'El informe de laboratorio o de experimento',link:'55',page:'106'},{name:'El informe de laboratorio o de experimento',link:'56',page:'109'},{name:'Subrayado y resumen',link:'57',page:'110'},{name:'Subrayado y resumen',link:'58',page:'110'},{name:'Subrayado y resumen',link:'59',page:'111'},{name:'Escritura de un informe – informe de laboratorio',link:'60',page:'112'},{name:'Escritura de un informe – informe de laboratorio',link:'61',page:'112'},{name:'Escritura de un informe – informe de laboratorio',link:'62',page:'113'},{name:'Conectores lógicos',link:'uni3a1',page:'114'},{name:'Conectores lógicos',link:'uni3a2',page:'114'},{name:'Conectores lógicos',link:'uni3a3',page:'115'},{name:'Oraciones según la naturaleza del verbo',link:'uni3a4',page:'116'},{name:'Oraciones según la naturaleza del verbo',link:'uni3a5',page:'116'},{name:'Oraciones según la naturaleza del verbo',link:'uni3a6',page:'117'},{name:'Uso de la tilde en pronombres interrogativos y exclamativos',link:'uni3a7',page:'118'},{name:'Uso de la tilde en pronombres interrogativos y exclamativos',link:'uni3a8',page:'118'},{name:'Uso de la tilde en pronombres interrogativos y exclamativos',link:'uni3a9',page:'118'},{name:'Uso de g y j en los verbos conjugados',link:'uni3a10',page:'119'},{name:'Uso de g y j en los verbos conjugados',link:'uni3a11',page:'119'},{name:'Uso de g y j en los verbos conjugados',link:'uni3a12',page:'119'},{name:'La cultura griega y sus textos representativos',link:'uni3a13',page:'122'},{name:'La cultura griega y sus textos representativos',link:'uni3a14',page:'122'},{name:'La cultura griega y sus textos representativos',link:'uni3a15',page:'124'},{name:'Evaluación sumativa',link:'63',page:'130'},]},
        {name:'UNIDAD 4',items:[{name:'El teatro en el Ecuador',link:'64',page:'138'},{name:'El teatro en el Ecuador',link:'65',page:'138'},{name:'El teatro en el Ecuador',link:'66',page:'144'},{name:'Mi monólogo',link:'67',page:'146'},{name:'Mi comedia costumbrista',link:'68',page:'147'},{name:'Las alteraciones del mensaje',link:'69',page:'148'},{name:'Las alteraciones del mensaje',link:'70',page:'148'},{name:'Las alteraciones del mensaje',link:'71',page:'149'},{name:'Lectura de documentos gráficos',link:'72',page:'150'},{name:'Lectura de documentos gráficos',link:'73',page:'150'},{name:'Lectura de documentos gráficos',link:'74',page:'151'},{name:'Estrategia de comprensión: lectura de mapas mentales',link:'75',page:'152'},{name:'Estrategia de comprensión: lectura de mapas mentales',link:'76',page:'152'},{name:'Estrategia de comprensión: lectura de mapas mentales',link:'77',page:'153'},{name:'Ambigüedades y contradicciones',link:'78',page:'154'},{name:'Ambigüedades y contradicciones',link:'79',page:'154'},{name:'Ambigüedades y contradicciones',link:'80',page:'155'},{name:'Escribir un texto a partir de una tabla estadística y un mapa mental',link:'uni4act1',page:'156'},{name:'Escribir un texto a partir de una tabla estadística y un mapa mental',link:'uni4act2',page:'156'},{name:'Escribir un texto a partir de una tabla estadística y un mapa mental',link:'uni4act3',page:'158'},{name:'Frases preposicionales, adverbiales y verbales',link:'uni4act4',page:'160'},{name:'Frases preposicionales, adverbiales y verbales',link:'uni4act5',page:'160'},{name:'Frases preposicionales, adverbiales y verbales',link:'uni4act6',page:'161'},{name:'Hiperónimos, hipónimos, homónimos, homófonos y parónimos',link:'uni4act7',page:'162'},{name:'Hiperónimos, hipónimos, homónimos, homófonos y parónimos',link:'uni4act8',page:'162'},{name:'Hiperónimos, hipónimos, homónimos, homófonos y parónimos',link:'uni4act9',page:'163'},{name:'Texto representativos de la América Prehispánica',link:'uni4act10',page:'166'},{name:'Texto representativos de la América Prehispánica',link:'uni4act11',page:'166'},{name:'Texto representativos de la América Prehispánica',link:'uni4act12',page:'169'},{name:'Evaluación sumativa',link:'uni4act13',page:'174'},]},
        ]
    },
    {
        name: 'ANIMACIONES',
        folder: 'animaciones',
        items: [
            {name:'UNIDAD 1',items:[{name:'El género dramático',link:'1',page:'14'},{name:'Lectura expresiva',link:'2',page:'20'},{name:'Honestidad intelectual, plagio y paráfrasis',link:'3',page:'24'},{name:'Formas de citación',link:'4',page:'28'},{name:'Oración compuesta por yuxtaposición',link:'5',page:'32'},{name:'Pronombres átonos y complementos directo e indirecto',link:'6',page:'35'},{name:'Variedades lingüísticas',link:'7',page:'39'},{name:'Organizo mis ideas',link:'8',page:'45'},]},
            {name:'UNIDAD 2',items:[{name:'Estructura interna de una obra del género dramático',link:'9',page:'55'},{name:'Estructura externa de una obra del género dramático. Roles del montaje escénico',link:'10',page:'58'},{name:'Importancia de la oralidad en la comunicación',link:'11',page:'62'},{name:'Texto expositivo',link:'12',page:'66'},{name:'Idea principal e ideas secundarias',link:'13',page:'68'},{name:'Cita textual larga',link:'14',page:'70'},{name:'Escritura de un texto expositivo',link:'15',page:'72'},{name:'Locuciones conjuntivas',link:'16',page:'74'},{name:'Diálogos directos e indirectos',link:'17',page:'76'},{name:'Registros de la lengua y estereotipos',link:'18',page:'80'},{name:'Organizo mis ideas',link:'19',page:'87'},]},
            {name:'UNIDAD 3',items:[{name:'Los subgéneros dramáticos menores',link:'20',page:'97'},{name:'Los subgéneros dramáticos menores',link:'21',page:'99'},{name:'Los subgéneros dramáticos menores',link:'22',page:'100'},{name:'La oratoria: declamación y discurso',link:'23',page:'104'},{name:'El informe de laboratorio o de experimento',link:'24',page:'106'},{name:'El informe de laboratorio o de experimento',link:'25',page:'108'},{name:'Subrayado y resumen',link:'26',page:'110'},{name:'Escritura de un informe – informe de laboratorio',link:'27',page:'112'},{name:'Conectores lógicos',link:'28',page:'114'},{name:'Oraciones según la naturaleza del verbo',link:'29',page:'116'},{name:'Uso de la tilde en pronombres interrogativos y exclamativos',link:'30',page:'118'},{name:'Uso de g y j en los verbos conjugados',link:'31',page:'119'},{name:'La cultura griega y sus textos representativos',link:'32',page:'122'},{name:'Organizo mis ideas',link:'33',page:'129'},]},
            {name:'UNIDAD 4',items:[{name:'El teatro en el Ecuador',link:'34',page:'138'},{name:'El teatro en el Ecuador',link:'35',page:'143'},{name:'Las alteraciones del mensaje',link:'36',page:'148'},{name:'Lectura de documentos gráficos.',link:'37',page:'151'},{name:'Estrategia de comprensión: lectura de mapas mentales',link:'38',page:'152'},{name:'Ambigüedades y contradicciones',link:'39',page:'154'},{name:'Escribir un texto a partir de una tabla estadística y un mapa mental',link:'40',page:'157'},{name:'Frases preposicionales, adverbiales y verbales',link:'41',page:'160'},{name:'Hiperónimos, hipónimos, homónimos, homófonos y parónimos',link:'42',page:'162'},{name:'Texto representativos de la América prehispánica',link:'43',page:'166'},{name:'Organizo mis ideas',link:'44',page:'173'},]},
        ]
    }
]

